www/src/Entity/Projet.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjetRepository")
 */
class Projet
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $client;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TypeProjet", inversedBy="projets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $typeProjet;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $budget;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $deadline;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="projets")
     */
    private $equipe;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Metier", inversedBy="projets")
     */
    private $equipe_necessaire;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="my_projects")
     */
    private $chef_projet;


    public function __construct()
    {
        $this->equipe = new ArrayCollection();
        $this->equipe_necessaire = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getClient(): ?string
    {
        return $this->client;
    }

    public function setClient(string $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTypeProjet(): ?TypeProjet
    {
        return $this->typeProjet;
    }

    public function setTypeProjet(?TypeProjet $typeProjet): self
    {
        $this->typeProjet = $typeProjet;

        return $this;
    }

    public function getBudget(): ?float
    {
        return $this->budget;
    }

    public function setBudget(?float $budget): self
    {
        $this->budget = $budget;

        return $this;
    }

    public function getDeadline(): ?\DateTimeInterface
    {
        return $this->deadline;
    }

    public function setDeadline(?\DateTimeInterface $deadline): self
    {
        $this->deadline = $deadline;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getEquipe(): Collection
    {
        return $this->equipe;
    }

    public function addEquipe(User $equipe): self
    {
        if (!$this->equipe->contains($equipe)) {
            $this->equipe[] = $equipe;
        }

        return $this;
    }

    public function removeEquipe(User $equipe): self
    {
        if ($this->equipe->contains($equipe)) {
            $this->equipe->removeElement($equipe);
        }

        return $this;
    }

    /**
     * @return Collection|Metier[]
     */
    public function getEquipeNecessaire(): Collection
    {
        return $this->equipe_necessaire;
    }

    public function addEquipeNecessaire(Metier $equipeNecessaire): self
    {
        if (!$this->equipe_necessaire->contains($equipeNecessaire)) {
            $this->equipe_necessaire[] = $equipeNecessaire;
        }

        return $this;
    }

    public function removeEquipeNecessaire(Metier $equipeNecessaire): self
    {
        if ($this->equipe_necessaire->contains($equipeNecessaire)) {
            $this->equipe_necessaire->removeElement($equipeNecessaire);
        }

        return $this;
    }

    public function getChefProjet(): ?User
    {
        return $this->chef_projet;
    }

    public function setChefProjet(?User $chef_projet): self
    {
        $this->chef_projet = $chef_projet;

        return $this;
    }

}

www/src/Form/ProjetType.php
<?php

namespace App\Form;

use App\Entity\Projet;
use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;

class ProjetType extends AbstractType
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //dd($this->security->getUser());

        $builder
            ->add('title')
            ->add('client')
            ->add('description');
            if($this->security->getUser()->isAdmin()){
                $builder->add('chef_projet');
            } else {
                $builder->add('equipe');
            }
        $builder->add('typeProjet')
                ->add('budget')
                ->add('deadline', DateType::class)
                ->add('equipe_necessaire');
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Projet::class,
        ]);
    }
}

www/src/Controller/Back/ProjetController.php
<?php

namespace App\Controller\Back;

use App\Entity\Projet;
use App\Entity\TypeProjet;
use App\Entity\User;
use App\Form\ProjetType;
use App\Repository\MetierRepository;
use App\Repository\ProjetRepository;
use App\Repository\TypeProjetRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/projet")
 */
class ProjetController extends AbstractController
{
    /**
     * @Route("/", name="projet_index", methods={"GET"})
     */
    public function index(ProjetRepository $projetRepository, TypeProjetRepository $typeProjetRepository): Response
    {
        return $this->render('projet/index.html.twig', [
            'projets_user' => $projetRepository->findAll(),
            'typeProjets' => $typeProjetRepository->findAll()
        ]);
    }

    /**
     * @Route("/new", name="projet_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $projet = new Projet();
        $form = $this->createForm(ProjetType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($projet);
            $entityManager->flush();

            return $this->redirectToRoute('admin_projet_index');
        }

        return $this->render('projet/new.html.twig', [
            'projet' => $projet,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="projet_show", methods={"GET"})
     */
    public function show(Projet $projet, UserRepository $userRepository,ProjetRepository $projetRepository, TypeProjetRepository $typeProjetRepository): Response
    {


        return $this->render('projet/show.html.twig', [
            'projet' => $projet,
            'chef_projets' => $userRepository->findByMetier('chef_projet'),
            'projets' => $projetRepository->findAll(),
            'typeProjets' => $typeProjetRepository->findAll()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="projet_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Projet $projet): Response
    {
        $form = $this->createForm(ProjetType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_projet_index');
        }

        return $this->render('projet/edit.html.twig', [
            'projet' => $projet,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="projet_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Projet $projet): Response
    {
        if ($this->isCsrfTokenValid('delete'.$projet->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($projet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_projet_index');
    }

    /**
     * @Route("/{id}/affect/{user_id}", name="projet_affect_chef", methods={"GET"})
     *
     * @param Request $request
     */
    public function affectChefProjet(Request $request, Projet $projet, UserRepository $userRepository): Response
    {
        $user = $userRepository->findOneBy(['id' => $request->get('user_id')]);
        $projet->setChefProjet($user);
        $user->addMyProject($projet);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->flush();

        return $this->redirectToRoute('admin_projet_show', ['id' => $projet->getId()]);
    }

    /**
     * @Route("?filter['metier']={id}", name="projet_filter_type", methods={"GET"})
     *
     * @param Request $request
     * @return Response
     */
    public function filterProjectsByType(Request $request, Projet $projet, ProjetRepository $projetRepository, TypeProjetRepository $typeProjetRepository): Response
    {
        $projets = $projetRepository->findByTypeProjet($request->get('id'));

        return $this->render('projet/index.html.twig', [
            'projets_user' => $projets,
            'typeProjets' => $typeProjetRepository->findAll()
        ]);
    }

    /**
     * @Route("?filter['status']={status}", name="projet_filter_status", methods={"GET"})
     *
     * @param Request $request
     * @return Response
     */
    public function filterProjetsByStatus(Request $request, ProjetRepository $projetRepository, TypeProjetRepository $typeProjetRepository): Response
    {
        $status = $request->get('status');
        $projets = [];
        if ($status == "disponible") {
            $projets = $projetRepository->findDisponible();
            return $this->render('projet/indexDispo.html.twig', [
                'projets_user' => $projets,
                'typeProjets' => $typeProjetRepository->findAll()
            ]);
        }
        else {
            $projets = $projetRepository->findNonDisponible();
            return $this->render('projet/indexNonDispo.html.twig', [
                'projets_user' => $projets,
                'typeProjets' => $typeProjetRepository->findAll()
            ]);
        }


    }
}

www/templates/projet/_delete_form.html.twig
<form method="post" action="{{ path('admin_projet_delete', {'id': projet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ projet.id) }}">
    <button class="btn btn-warning">Delete</button>
</form>

www/templates/projet/_form.html.twig
{{ form_start(form) }}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <label for="inputEmail">Title</label>
                    {{ form_widget(form.title, {'attr' : {'class' : 'form-control'}}) }}
                </div>
                <div class="form-group">
                    <label for="inputEmail">Client</label>
                    {{ form_widget(form.client, {'attr' : {'class' : 'form-control'}}) }}
                </div>
                <div class="form-group">
                    <label for="inputEmail">Description</label>
                    {{ form_widget(form.description, {'attr' : {'class' : 'form-control'}}) }}
                </div>
                {% if is_granted('ROLE_ADMIN') %}
                    <div class="form-group">
                        <label for="inputEmail">Chef de projet</label>
                        {{ form_widget(form.chef_projet, {'attr' : {'class' : 'form-control'}}) }}
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="inputEmail">Equipe</label>
                        {{ form_widget(form.equipe, {'attr' : {'class' : 'form-control'}}) }}
                    </div>
                {% endif %}
                <div class="form-group">
                    <label for="inputEmail">TypeProjet</label>
                    {{ form_widget(form.typeProjet, {'attr' : {'class' : 'form-control'}}) }}
                </div>
                <div class="form-group">
                    <label for="inputEmail">Budget</label>
                    {{ form_widget(form.budget, {'attr' : {'class' : 'form-control'}}) }}
                </div>
                <div class="form-group">
                    <label for="inputEmail">Deadline</label>
                    {{ form_widget(form.deadline, {'attr' : { 'type':'date'}}) }}
                </div>
                <div class="form-group">
                    <label for="inputEmail">Equipe_necessaire</label>
                    {{ form_widget(form.equipe_necessaire, {'attr' : {'class' : 'form-control'}}) }}
                </div>
                <button class="btn btn-warning">{{ button_label|default('Save') }}</button>
            </div>
        </div>
    </div>
</div>
{{ form_end(form) }}

www/templates/projet/edit.html.twig
{% extends 'back/base_admin.html.twig' %}
{% block title %}Edit Projet{% endblock %}

{% block content %}
    <h1><b>Edit Projet </b><a href="{{ path('admin_projet_index') }}" class="btn btn-warning" type="button">Back to
            list</a> </h1>
    {{ include('projet/_delete_form.html.twig') }}
    <br>
    {{ include('projet/_form.html.twig', {'button_label': 'Update'}) }}



{% endblock %}

www/templates/projet/index.html.twig
{% extends 'back/base_admin.html.twig' %}

{% block title %}Les missions{% endblock %}

{% block content %}
    <h3>Les</h3>
    <h3><b>missions</b><H3>
    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('admin_projet_new') }}" type="button" class="btn btn-warning"
                           style="color: black"><b>Create new</b></a>
    <br>

    <div class="col-md-6">
        <div class="d-inline-flex justify-content-between">
            <a style="color: black;" class=""
               href="{{ path('admin_projet_filter_status', {status : "disponible"}) }}"><b>A
                    PROPOSER</b></a>

            <a style="margin-left: 2em; color: black;" class=""
               href="{{ path('admin_projet_filter_status', {status : "non_disponible"}) }}"><b>EN
                    COURS</b></a>
        </div>
    </div>
    <br>
    <!-- Grid row -->
    <div class="row">

        <!-- Grid column -->
        <div class="col-md-10 col-xl-8 d-inline-flex flex-wrap">
            <a class="btn btn-outline-black" href="{{ path('admin_projet_index') }}" role="tab"
               style="color: black; border-radius: 10px;"><b>TOUS</b></a>
            {% for type in typeProjets %}
                <a class="btn btn-outline-black" href="{{ path('admin_projet_filter_type', {'id': type.id}) }}" role="tab"
                   style="color: black; border-radius: 10px;"><b>{{ type.title }}</b></a>
            {% endfor %}
        </div>
        <!-- Grid column -->

    </div>
    <br>
    {% endif %}

    {% if app.user.isChefProjet() == true %}
            <!-- Card deck -->

            <div class="row col-md-12">
                <div class="d-inline-flex justify-content-between flex-wrap align-items-center">
                    {% for projet in projets_chef %}
                        <!-- Card -->
                        <div style="height: 600px;">
                            <div class="card" style="width: 400px; height: 500px;">

                                <!--Card content-->
                                <div class="card-body">

                                    <!--Title-->
                                    <h4 class="card-title text-center">{{ projet.title }}</h4>

                                    <!--Client -->
                                    <p class="client-title text-center">{{ projet.client }}</p>

                                    <p><b>Budget :</b> {{ (projet.budget == null ) ? 0 : projet.budget }}€</p>
                                    <p><b>Deadline :</b> {{ projet.deadline|date("m/d/Y") }}</p>
                                    <b>Équipe nécessaire :</b>
                                    <p>
                                    <ul>
                                        {% for metier in projet.equipeNecessaire %}
                                            <li>{{ metier }}</li>
                                        {% endfor %}
                                    </ul>
                                    </p>
                                    <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
                                    <div class="text-center">
                                        {% if is_granted('ROLE_ADMIN') %}
                                            <a href="{{ path('admin_projet_show', {'id': projet.id}) }}"
                                           class="btn btn-warning" style="color: black"><b>DÉTAILS</b></a>
                                        {% else %}
                                            <a href="{{ path('user_show_mission', {'id': projet.id}) }}"
                                               class="btn btn-warning" style="color: black"><b>DÉTAILS</b></a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Card deck -->
    {% endif %}
    <!-- Card deck -->

    <div class="row col-md-12">
        <div class="d-inline-flex justify-content-between flex-wrap align-items-center">
            {% for projet in projets_user %}
                <!-- Card -->
                <div style="height: 600px;">
                    <div class="card" style="width: 400px; height: 500px;">

                        <!--Card content-->
                        <div class="card-body">

                            <!--Title-->
                            <h4 class="card-title text-center">{{ projet.title }}</h4>

                            <!--Client -->
                            <p class="client-title text-center">{{ projet.client }}</p>

                            <p><b>Budget :</b> {{ (projet.budget == null ) ? 0 : projet.budget }}€</p>
                            <p><b>Deadline :</b> {{ projet.deadline|date("m/d/Y") }}</p>
                            <b>Équipe nécessaire :</b>
                            <p>
                            <ul>
                                {% for metier in projet.equipeNecessaire %}
                                    <li>{{ metier }}</li>
                                {% endfor %}
                            </ul>
                            </p>
                            <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
                            <div class="text-center">
                                <a href="{{ path('admin_projet_show', {'id': projet.id}) }}"
                                   class="btn btn-warning" style="color: black"><b>DÉTAILS</b></a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- Card deck -->


{% endblock %}

www/templates/projet/indexDispo.html.twig
{% extends 'back/base_admin.html.twig' %}

{% block title %}Les missions{% endblock %}

{% block content %}
    <h3>Les</h3>
    <h3><b>missions</b> <a href="{{ path('admin_projet_new') }}" type="button" class="btn btn-warning"
                           style="color: black"><b>Create new</b></a>
    </h3>
    <br>

    <div class="col-md-6">
        <div class="d-inline-flex justify-content-between">
            <a style="color: black;" class=""
               href="{{ path('admin_projet_filter_status', {status : "disponible"}) }}"><b><img
                            src="https://cdn.discordapp.com/attachments/684871801901154331/685221267653394445/Group_14.png"></b></a>

            <a style="margin-left: 2em; color: black;" class=""
               href="{{ path('admin_projet_filter_status', {status : "non_disponible"}) }}"><b>EN
                    COURS</b></a>
        </div>
    </div>
    <br>
    <!-- Grid row -->
    <div class="row">

        <!-- Grid column -->
        <div class="col-md-10 col-xl-8 d-inline-flex flex-wrap">
            <a class="btn btn-outline-black" href="{{ path('admin_projet_index') }}" role="tab"
               style="color: black; border-radius: 10px;"><b>TOUS</b></a>
            {% for type in typeProjets %}
                <a class="btn btn-outline-black" href="{{ path('admin_projet_filter_type', {'id': type.id}) }}"
                   role="tab"
                   style="color: black; border-radius: 10px;"><b>{{ type.title }}</b></a>
            {% endfor %}
        </div>
        <!-- Grid column -->

    </div>
    <br>

    <!-- Card deck -->

    <div class="row col-md-12">
        <div class="d-inline-flex justify-content-between flex-wrap align-items-center">
            {% for projet in projets %}
                <!-- Card -->
                <div style="height: 600px;">
                    <div class="card" style="width: 400px; height: 500px;">

                        <!--Card content-->
                        <div class="card-body">

                            <!--Title-->
                            <h4 class="card-title text-center">{{ projet.title }}</h4>

                            <!--Client -->
                            <p class="client-title text-center">{{ projet.client }}</p>

                            <p><b>Budget :</b> {{ (projet.budget == null ) ? 0 : projet.budget }}€</p>
                            <p><b>Deadline :</b> {{ projet.deadline|date("m/d/Y") }}</p>
                            <b>Équipe nécessaire :</b>
                            <p>
                            <ul>
                                {% for metier in projet.equipeNecessaire %}
                                    <li>{{ metier }}</li>
                                {% endfor %}
                            </ul>
                            </p>
                            <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
                            <div class="text-center">
                                <a href="{{ path('admin_projet_show', {'id': projet.id}) }}"
                                   class="btn btn-warning" style="color: black"><b>DÉTAILS</b></a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- Card deck -->


{% endblock %}

www/templates/projet/new.html.twig
{% extends 'back/base_admin.html.twig' %}
{% block title %}New Projet{% endblock %}

{% block content %}
    <h1>Create new Projet <a href="{{ path('admin_projet_index') }}" class="btn btn-warning" type="button">Back to
            list</a></h1>


    {{ include('projet/_form.html.twig') }}


{% endblock %}

www/templates/projet/show.html.twig
{% extends 'back/base_admin.html.twig' %}

{% block title %}Projet index{% endblock %}

{% block content %}
    <h3>Les</h3>
    <h3><b>missions</b> <a href="{{ path('admin_projet_new') }}" type="button" class="btn btn-warning"
                           style="color: black"><b>Create new</b></a>
    </h3>
    <br>

    <div class="col-md-6">
        <div class="d-inline-flex justify-content-between">
            <a style="color: black;" class=""
               href="{{ path('admin_projet_filter_status', {status : "disponible"}) }}"><b>A
                    PROPOSER</b></a>

            <a style="margin-left: 2em; color: black;" class=""
               href="{{ path('admin_projet_filter_status', {status : "non_disponible"}) }}"><b>EN
                    COURS</b></a>
        </div>
    </div>
    <br>
    <div class="row">

        <!-- Grid column -->
        <div class="col-md-10 col-xl-8 d-inline-flex flex-wrap">
            <a class="btn btn-outline-black" href="{{ path('admin_projet_index') }}" role="tab"
               style="color: black; border-radius: 10px;"><b>TOUS</b></a>
            {% for type in typeProjets %}
                <a class="btn btn-outline-black" href="{{ path('admin_projet_filter_type', {'id': type.id}) }}" role="tab"
                   style="color: black; border-radius: 10px;"><b>{{ type.title }}</b></a>
            {% endfor %}
        </div>
        <!-- Grid column -->

    </div>
    <br>
    <div class="">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="col-md-2 text-center">
                            <h1 class="projet-titre">{{ projet.title }} <a type="button" class="btn btn-warning"
                                                                           href="{{ path('admin_projet_edit', {'id': projet.id}) }}">Edit</a>
                            </h1>
                            <p>{{ projet.client }}</p>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-6">

                                <p><b>Budget :</b> {{ (projet.budget == null ) ? 0 : projet.budget }}€</p>
                                <p><b>Équipe nécessaire :</b>
                                <ul>
                                    {% for metier in projet.equipeNecessaire %}
                                        <li>{{ metier }}</li>
                                    {% endfor %}
                                </ul>
                                </p>
                                <p><b>Deadline : </b>{{ projet.deadline|date('d/m/Y') }}</p>
                            </div>
                            <div class="col-md-6">

                                <p><b>Description : </b></p>
                                <p>{{ projet.description }}</p>
                                <p><b>Livrable : </b></p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <b>Propositions de profils : </b>
                            <div class="row row-cols-1 row-cols-md-4">
                                {% if projet.chefProjet != null %}
                                    <div class="col mb-3">
                                        <div class="card text-center d-flex align-items-center text-dark">
                                            <br>
                                            <div class="avatar mx-auto white">
                                                <img height="100px" width="100px"
                                                     src="https://mdbootstrap.com/img/Photos/Avatars/img%20%2810%29.jpg"
                                                     class="rounded-circle"
                                                     alt="woman avatar">
                                            </div>
                                            <!-- Content -->
                                            <div class="card-body text-center">
                                                <!-- Name -->
                                                <h4 class="card-title">{{ projet.chefProjet.lastname }}</h4>
                                                <h4 class="card-title">{{ projet.chefProjet.firstname }}</h4>

                                                <span>Secteur privilégié : <b>All</b></span><br>
                                                <span>Taux journalier : <b>{{ projet.chefProjet.tauxJournalier }}€</b></span><br>
                                                <span>Rémunération projet : <b>{{ projet.chefProjet.tauxJournalier }}€</b></span>

                                            </div>
                                            <a type="button" class="btn btn-warning">
                                                <b>ATTRIBUÉ</b></a>
                                            <br>
                                        </div>

                                    </div>
                                {% else %}
                                    {% for chef in chef_projets %}
                                        <!-- Card -->
                                        <div class="col mb-4">
                                            <div class="card text-center d-flex align-items-center text-dark">

                                                <div class="avatar mx-auto white">
                                                    <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20%2810%29.jpg"
                                                         class="rounded-circle"
                                                         alt="woman avatar">
                                                </div>
                                                <!-- Content -->
                                                <div class="card-body">
                                                    <!-- Name -->
                                                    <h4 class="card-title">{{ chef.lastname }}</h4>
                                                    <h4 class="card-title">{{ chef.firstname }}</h4>

                                                    <span>Taux journalier : <b>{{ chef.tauxJournalier }}€</b></span><br>
                                                    <span>Rémunération projet : <b>{{ chef.tauxJournalier }}€</b></span>

                                                </div>
                                                <a class="btn btn-warning" style="color: black;"
                                                   href="{{ path("admin_projet_affect_chef", {id: projet.id, user_id: chef.id}) }}">
                                                    <b>ATTRIBUER</b></a>
                                                <br>
                                            </div>

                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}